# Generated by Django 3.0.3 on 2020-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(default=None, to='recipe_box.Author'),
        ),
    ]
